<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SpatialLauncher.Desktop.Core</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Concentus" Version="2.2.2" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime.DirectML" Version="1.19.2" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.8" />
    <PackageReference Include="System.Speech" Version="8.0.0" />
    <PackageReference Include="Vortice.MediaFoundation" Version="3.6.2" />
  </ItemGroup>
</Project>
